# This is a basic workflow to help you get started with Actions

name: run_test

on: 
  push:
    branches: master

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run GitHub Action Tests
    steps:

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Print Public IP
        run: dig +short myip.opendns.com @resolver1.opendns.com

#      - name: Create Resource Group for the NSG
#        run: az group create -l australiaeast -n ManageNsg
      
#      - name: Create the NSG
#        run: az network nsg create -g ManageNsg -n ManageNsg

      - name: Add NSG Rule
        uses: venura9/manage-nsg@master
        id: rule
        with:
          azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Created NSG Rule Name
        run: echo "Rule Name ${{ steps.rule.outputs.rule_name }}"

      - name: Remove NSG Rule
        uses: venura9/manage-nsg@master
        with:
          azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}
          rule-id-for-removal: ${{ steps.rule.outputs.rule_name }}
    
    
