# This is a basic workflow to help you get started with Actions

name: run_test

on: 
  push:
    branches: master

jobs:
  test:
    runs-on: ubuntu-latest
    name: Testing the Action
    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Print the current runners public ip
        run: dig +short myip.opendns.com @resolver1.opendns.com 
      
      # To use this repository's private action, you must check out the repository
      - name: Add the rule for the current agent IP
        uses: venura9/manage-nsg@master
        id: hello
        with:
          who-to-greet: 'Mona the Octocat'
          azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
    
    
