# This is a basic workflow to help you get started with Actions

name: run_test

on: 
  push:
    branches: master

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run GitHub Action Tests
    steps:

      - name: Print Public IP
        run: dig +short myip.opendns.com @resolver1.opendns.com 
      
      # To use this repository's private action, you must check out the repository
      - name: Add NSG Rule
        uses: venura9/manage-nsg@master
        id: rule
        with:
          azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}
      # Use the output from the `hello` step
      - name: Created NSG Rule Name
        run: echo "Rule Name ${{ steps.rule.outputs.name }}"
    
    
